### ISSUE TITLE
Psi is gooooone

### ISSUE THREAD

**Issue by benj8560** [VestaOfOrion/Vesta.Bay#103]
#### Description of issue
Bay seems to have fully removed psionics. Felt this should go here since its completely destroyed psionic advisors their job no longer exists outside of admin events. Since we started playing on the rebase I noticed a massive lack of pykers as psi advisors sure enough I started sweeping player panels and noticed in fact there was not a single one.

Other players noticed this as well also this goes as far as Mules not even getting forced latencies you can even hear them get removed when you spawn in as one. I looked around on Bays git and could not find a pull about it could just be a config issue as well but I'm not sure regardless sure does need a fix.

Edit: to be clear it removes the RND from psionics

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 1d198add1aa2dce2d3b89fc01d711315abc8d249 - - 2020-12-20
Game ID: b0I-bGdW

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Vizoplez** [comment]
To clarify; Psionics is seemingly being removed on character creation; going as far to as play the noise of it being admin-removed. This can be tested via becoming a mule; or any other way of forcing yourself to spawn with Psionics.

**Comment by r4iser** [comment]
Psionics were not removed at all. The thing is around the chances to be psionics on Bay is just at 1%.

We've raised it to 5%, just like how it was on old Vesta. [Here.](https://github.com/VestaOfOrion/Vesta.Bay/pull/54)

"To clarify; Psionics is seemingly being removed on character creation". Join as Psionic Advisor and check out psionics.

**Comment by Vizoplez** [comment]
> Psionics were not removed at all. The thing is around the chances to be psionics on Bay is just at 1%.
> 
> We've raised it to 5%, just like how it was on old Vesta. [Here.](https://github.com/VestaOfOrion/Vesta.Bay/pull/54)
> 
> "To clarify; Psionics is seemingly being removed on character creation". Join as Psionic Advisor and check out psionics.

This is different; psionic advisor has its psionics manually changed. Mules, etcetera, seemingly have it stripped. The way PADV has it applied is also different.

**Comment by r4iser** [comment]
> > Psionics were not removed at all. The thing is around the chances to be psionics on Bay is just at 1%.
> > We've raised it to 5%, just like how it was on old Vesta. [Here.](https://github.com/VestaOfOrion/Vesta.Bay/pull/54)
> > "To clarify; Psionics is seemingly being removed on character creation". Join as Psionic Advisor and check out psionics.
> 
> This is different; psionic advisor has its psionics manually changed. Mules, etcetera, seemingly have it stripped. The way PADV has it applied is also different.

Yeah, I was just pointing you that it was not removed from character creation. Other than this, all other does the same 5% roll, even on old Vesta.
Any other job or mob should have it manually set, other than the Psionic Advisor?

**Comment by Vizoplez** [comment]
> > > Psionics were not removed at all. The thing is around the chances to be psionics on Bay is just at 1%.
> > > We've raised it to 5%, just like how it was on old Vesta. [Here.](https://github.com/VestaOfOrion/Vesta.Bay/pull/54)
> > > "To clarify; Psionics is seemingly being removed on character creation". Join as Psionic Advisor and check out psionics.
> > 
> > 
> > This is different; psionic advisor has its psionics manually changed. Mules, etcetera, seemingly have it stripped. The way PADV has it applied is also different.
> 
> Yeah, I was just pointing you that it was not removed from character creation. Other than this, all other does the same 5% roll, even on old Vesta.
> Any other job or mob should have it manually set, other than the Psionic Advisor?

All Mules should have psionics per default (latent, not awakened); this is not the case as showcased by the 'psionic ascent' bug that happened for a while; but no longer occurs; and mules get the same thing. When you spawn as a provoc/offship with psionics, you get the loud 'psionics backblast' noise played, and your psionics removed.

**Comment by r4iser** [comment]
> > > > Psionics were not removed at all. The thing is around the chances to be psionics on Bay is just at 1%.
> > > > We've raised it to 5%, just like how it was on old Vesta. [Here.](https://github.com/VestaOfOrion/Vesta.Bay/pull/54)
> > > > "To clarify; Psionics is seemingly being removed on character creation". Join as Psionic Advisor and check out psionics.
> > > 
> > > 
> > > This is different; psionic advisor has its psionics manually changed. Mules, etcetera, seemingly have it stripped. The way PADV has it applied is also different.
> > 
> > 
> > Yeah, I was just pointing you that it was not removed from character creation. Other than this, all other does the same 5% roll, even on old Vesta.
> > Any other job or mob should have it manually set, other than the Psionic Advisor?
> 
> All Mules should have psionics per default (latent, not awakened); this is not the case as showcased by the 'psionic ascent' bug that happened for a while; but no longer occurs; and mules get the same thing. When you spawn as a provoc/offship with psionics, you get the loud 'psionics backblast' noise played, and your psionics removed.

So, translating: Mules should always be psionics but they arent. Is this correct?

**Comment by Superhats** [comment]
Mules should have a guarantee of spawning as a latent psion

**Comment by BurpleBineapple** [comment]
Which they do

`/datum/species/human/mule/handle_post_spawn(var/mob/living/carbon/human/H)
	if(!H.psi)
		H.psi = new(H)
		var/list/faculties = list("[PSI_COERCION]", "[PSI_REDACTION]", "[PSI_ENERGISTICS]", "[PSI_PSYCHOKINESIS]")
		for(var/i = 1 to rand(2,3))
			H.set_psi_rank(pick_n_take(faculties), 1)`

All mules get a 100% random latency for an operant/master level psionic by default on top of the 5% for extra latency
