### ISSUE TITLE
Security officer ballistic P20 pistol missing, why?

### ISSUE THREAD

**Issue by jdeuce22** [VestaOfOrion/Vesta.Bay#139]
#### Description of issue
I was playing security officer and noticed that there is no way to acquire the ballistic sidearm P20 pistol that's usually in the security officer equipment kit

#### Difference between expected and actual behavior
expected is that there is a ballistic choice actual is that there is not

#### Steps to reproduce
be sec officer, go to locker, get equipment kit, use equipment kit

#### Specific information for locating

equipment kit

#### Length of time in which bug has been known to occur

ever since the rebase

#### Client version, Server revision & Game ID

513
ab722b22848717e30eb75899bb02a88a71642ff0 - - 2020-12-26
b0N-dKVt
#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Mocha-Not-Latte** [comment]
Intentional.

**Comment by jdeuce22** [comment]
why? I found the P-20 quite good except for scenarios when you needed it to suddenly become lethal

**Comment by BurpleBineapple** [comment]
Security is being directed away from ballistic options in favor of tasers, as they cause less permanent damage to the victim with about the same pain infliction. This is intended.
