### ISSUE TITLE
Psionic Advisor can acquire MULTIPLE revolvers and MULTIPLE ammo

### ISSUE THREAD

**Issue by ghost** [VestaOfOrion/Vesta.Bay#140]
#### Description of issue
Psionic advisor can get two guns, three if there was a previous advisor.

#### Difference between expected and actual behavior
Psionic advisor is supposed to get one gun.

#### Steps to reproduce
Be psionic advisor
Go to locker, get gun
Go to briefcase you spawn with, get gun.

#### Specific information for locating

Outfit datum for psi advisor, contents of psi advisor locker

Since day of issue posting.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: ab722b22848717e30eb75899bb02a88a71642ff0 - - 2020-12-26
Game ID: b0N-dKVt
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurpleBineapple** [comment]
Solved in https://github.com/VestaOfOrion/Vesta.Bay/pull/147
