### ISSUE TITLE
The salvage rig's mining ship's solar panels cannot be detected at round start.

### ISSUE THREAD

**Issue by XElectricX** [VestaOfOrion/Vesta.Bay#189]
#### Description of issue
If you go to the solar console for the mining ship, it only detects the solar tracker. After a lot of trial and error searching for what the problem was, I deconstructed the panel and rebuilt one. It then becomes detected. Reconstructing each solar panel makes it detectable. Strange bit is that the other solar panels throughout the salvage rig work fine at round start without problems. Only the mining vessel has to have the panels rebuilt.

#### Difference between expected and actual behavior
Solar panels cannot be rotated by the solar console as they are not detected. It is expected for the panels to be detected round start.

#### Steps to reproduce
Load the salvage rig. Look at the mining vessel's solar console. It will only display the tracker as being detected.

#### Specific information for locating
The green ship with mining equipment. The solar console and panels are on the west side, next to the SMES and cockpit.

#### Length of time in which bug has been known to occur
Round start.

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: 04cd3c04d0c4eaa843064df531f9e9a7acad3519 - - 2020-12-31
Game ID: b0S-avAW
Current map: NTSS Dagon

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by du-top** [comment]
I tried to reproduce the issue by doing following:
- Started local test server
- Fun-> "Map template - Place in new Z" ->"Salvage Gantry"
- Admin -> "Jump to Area" -> "Upper Salvage Gantry Arm"
- Found something green, found a Solars console outside
- "Search for devices": Solar Panels: 8 connected. 

Is the issue already fixed?
Did my (try-and-error-)way of reproducing the error circumvent the error's occurrence? If so, could I get more detailed step-by-step reproduction information?
