### ISSUE TITLE
Windows not opaque when lacking grille

### ISSUE THREAD

**Issue by Pebblesthe2nd** [VestaOfOrion/Vesta.Bay#283]
#### Description of issue
Windows without grilles look non-opaque

#### Difference between expected and actual behavior
I mean the ones with grilles are still opaque

#### Steps to reproduce
Look

#### Specific information for locating
Torch

#### Length of time in which bug has been known to occur
Today

#### Client version, Server revision & Game ID
Client Version:  513 
Server Revision:  9c9fe8c6e0f2544c21066acd0f2d1223071ae5cb  - - 2021-01-10 

#### Issue bingo
- [ ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurpleBineapple** [comment]
I'm not sure I understand. This doesn't seem like a bug, just a stylistic choice by whoever made window sprites.
