### ISSUE TITLE
Foundation agent have no operant registration cards

### ISSUE THREAD

**Issue by Noobetski** [VestaOfOrion/Vesta.Bay#288]
#### Description of issue

Half of foundation agent work is to locate and registr latents.

#### Difference between expected and actual behavior

Foundation agent should have operant registration cards to register psionics

#### Steps to reproduce

Spawn as foundation agent, see you have your operant registration card, but no blank ones

#### Specific information for locating
Foundation office, locker or character inventory

#### Length of time in which bug has been known to occur

Today

#### Client version, Server revision & Game ID

Every server, latest version

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by BurpleBineapple** [comment]
I'll need to talk to the lore maintainers about this, though I don't think it's the PADV's job to *register* psionics. They're there to locate them and contact the Foundation/NanoTrasen (depending on if you're an Agent or a NT Psion) and let them know of your findings.

Registering as a psion is a legal undertaking similar to applying for a license. The PADV however can easily make their own paperwork for "temporary" registration similar to a temporary drivers license.
