### ISSUE TITLE
Orbital Assault Beret unable to spawn in loadout

### ISSUE THREAD

**Issue by Yurektemp** [VestaOfOrion/Vesta.Bay#378]
#### Description of issue

The Orbital Assault Beret cannot be spawned with in loadout, despite being in-code.

#### Difference between expected and actual behavior

It should be spawnable in loadout.

#### Steps to reproduce

Look under SolGov Berets. It's not there.

#### Specific information for locating

/obj/item/clothing/head/beret/solgov/orbital
	name = "orbital assault beret"
	desc = "A blue beret denoting orbital assault training. For helljumpers that are more inclined towards style than safety."
	icon_state = "beret_blue"

#### Length of time in which bug has been known to occur

Since Rebayse, probably.

#### Client version, Server revision & Game ID

Server Revision: Revision Unknown
Game ID: ccN-btWo
Current map: NTSS Dagon

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues) <(THIS IS NOT THE CORRECT LINK, YOU MAY WANT TO FIX YOUR FORMAT)

**Comment by Alanii** [comment]
Orbital Assault Bere is now shown in loadout screen.
