### ISSUE TITLE
Mislabeled or missing sprite state for sleepers

### ISSUE THREAD

**Issue by Keekenox** [VestaOfOrion/Vesta.Bay#62]
sleepers either have a missing or mislabeled sprite state for when they are occupied.[https://i.imgur.com/vRK6Djn.png](url)

![image](https://user-images.githubusercontent.com/17456762/102710488-ad8edc00-4280-11eb-859a-df54979093f9.png)

**Comment by BurpleBineapple** [comment]
I'll take a look in a moment.

**Comment by BurpleBineapple** [comment]
Fixed
