### ISSUE TITLE
Adherent (spawn/language) lobby bugs

### ISSUE THREAD

**Issue by reklaw9** [VestaOfOrion/Vesta.Bay#75]
#### Difference between expected and actual behavior
1>being a adherent and being able to spawn as paramedic, counselor, surgeon and chaplain
1>being a adherent and-- [SPECIES RESTRICTED]

2>being a adherent and being able to have two of these languages as secondary: Gutter, Spacer and ZAC
2>being a adherent and not being able to have "gutter" as a language

#### Steps to reproduce

1>be a adherent and look at the "occupations" to see which jobs you can be
2>be a adherent and look at the "background" to see which languages you can select
#### Specific information for locating
 all of these bugs are found on the lobby 
 
 1>line 3 to 5 of "torch_jobs.dm"
 2>line 10 to 13 of "cultures_adherent.dm"

#### Length of time in which bug has been known to occur
Since we changed to the new codebase

#### Client version, Server revision & Game ID
Client Version: 513
Server Revision: e503d1b7402f9a3a8bb20de6644c8d75ba89b695 - - 2020-12-20
Game ID: b0H-bUI6
Current map: NTSS Dagon

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by BurpleBineapple** [comment]
Gutter is intentional. It is restricted only to Plutonians now.

I'll take a look at the jobs once I have a moment

**Comment by Superhats** [comment]
Job issues are resolved by #80
